from __future__ import annotations

KEY_NUTRIENTS = {
    "protein_g": ("Protein", "g", "宏量"),
    "fat_g": ("Total lipid (fat)", "g", "宏量"),
    "carb_g": ("Carbohydrate, by difference", "g", "宏量"),
    "ca_mg": ("Calcium, Ca", "mg", "矿物质"),
    "p_mg": ("Phosphorus, P", "mg", "矿物质"),
    "k_mg": ("Potassium, K", "mg", "矿物质"),
    "na_mg": ("Sodium, Na", "mg", "矿物质"),
    "mg_mg": ("Magnesium, Mg", "mg", "矿物质"),
    "fe_mg": ("Iron, Fe", "mg", "矿物质"),
    "zn_mg": ("Zinc, Zn", "mg", "矿物质"),
    "cu_mg": ("Copper, Cu", "mg", "矿物质"),
    "mn_mg": ("Manganese, Mn", "mg", "矿物质"),
    "se_ug": ("Selenium, Se", "µg", "矿物质"),
    "iodine_ug": ("Iodine, I", "µg", "矿物质"),
    "vit_a_ug": ("Vitamin A, RAE", "µg", "维生素"),
    "vit_d_ug": ("Vitamin D (D2 + D3)", "µg", "维生素"),
    "vit_e_mg": ("Vitamin E (alpha-tocopherol)", "mg", "维生素"),
    "thiamin_mg": ("Thiamin", "mg", "维生素"),
    "riboflavin_mg": ("Riboflavin", "mg", "维生素"),
    "niacin_mg": ("Niacin", "mg", "维生素"),
    "pantothenic_mg": ("Pantothenic acid", "mg", "维生素"),
    "vit_b6_mg": ("Vitamin B-6", "mg", "维生素"),
    "folate_ug": ("Folate, total", "µg", "维生素"),
    "vit_b12_ug": ("Vitamin B-12", "µg", "维生素"),
    "epa_g": ("20:5 n-3 (EPA)", "g", "EPA/DHA"),
    "dha_g": ("22:6 n-3 (DHA)", "g", "EPA/DHA"),
}

FDC_NUTRIENT_TO_KEY = {
    "1003": "protein_g",
    "1004": "fat_g",
    "1005": "carb_g",
    "1087": "ca_mg",
    "1091": "p_mg",
    "1092": "k_mg",
    "1093": "na_mg",
    "1090": "mg_mg",
    "1089": "fe_mg",
    "1095": "zn_mg",
    "1098": "cu_mg",
    "1101": "mn_mg",
    "1103": "se_ug",
    "1104": "vit_a_ug",
    "1114": "vit_d_ug",
    "1109": "vit_e_mg",
    "1165": "thiamin_mg",
    "1166": "riboflavin_mg",
    "1167": "niacin_mg",
    "1170": "pantothenic_mg",
    "1175": "vit_b6_mg",
    "1177": "folate_ug",
    "1178": "vit_b12_ug",
    "1278": "epa_g",
    "1272": "dha_g",
}

CN_ALIASES = {
    "鸡胸肉": ["chicken breast", "鸡胸", "鸡肉"],
    "鸡蛋": ["egg", "whole egg"],
    "牛心": ["beef heart", "heart"],
    "红薯": ["sweet potato"],
    "西蓝花": ["broccoli", "西兰花"],
}
